default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DB_HOST') { '127.0.0.1' } %>


development:
  <<: *default
  database: dyna_team_development

  username: <%= ENV.fetch('DATABASE_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>

test:
  <<: *default
  database: dyna_team_test

  username: <%= ENV.fetch('DATABASE_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>

production:
  primary: &primary_production
    <<: *default
    database: dyna_team_production
    username: dyna_team
    password: <%= ENV["DYNA_TEAM_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: dyna_team_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: dyna_team_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: dyna_team_production_cable
    migrations_paths: db/cable_migrate
